import numpy as np
from farc.apps.calculator import multi_room_generator
from farc.apps.calculator import multi_room_model



Ventilation1 = multi_room_model.Ventilation('mechanical_ventilation',10,1,1,'window_sliding',1,1,'windows_open_permanently',1,'January',1,'mech_type_air_supply',100,1000.,0)
Room1 = multi_room_model.Room('Test',100, Ventilation1, 1, 0.3, 20.,np.array([]),np.array([]))
Room2 = multi_room_model.Room('Test2', 100, Ventilation1, 2 ,0.3 ,20.,np.array([]),np.array([]))
Event1 = multi_room_model.Event(12, 16, Room1, 0.7, 'Type_I', 'Musculation')
Event2 = multi_room_model.Event(8, 8.1, Room1, 0.7, 'Type_I', 'Musculation')
Event3 = multi_room_model.Event(8.1, 8.3, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event4 = multi_room_model.Event(8.3, 8.5, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event5 = multi_room_model.Event(8.5, 8.8, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event6 = multi_room_model.Event(8.8, 9.3, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event7 = multi_room_model.Event(9.3, 9.8, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event8 = multi_room_model.Event(9.8, 10.5, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event9 = multi_room_model.Event(10.5, 10.8, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event10 = multi_room_model.Event(10.8, 11, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event11 = multi_room_model.Event(11, 11.2, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event12 = multi_room_model.Event(11.2, 11.4, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event13 = multi_room_model.Event(11.4, 11.6, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event14 = multi_room_model.Event(11.6, 11.8, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event15 = multi_room_model.Event(11.8, 11.9, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Event16 = multi_room_model.Event(11.9, 12, Room1, 0.7, 'Type_I', 'Concert_musician_rock')
Schedule1 = multi_room_model.Schedule(np.array([]))
Schedule1.add_event(Event1)
Schedule2 = multi_room_model.Schedule(np.array([]))
Schedule2.add_event(Event2)
Schedule2.add_event(Event3)
Schedule2.add_event(Event4)
Schedule2.add_event(Event5)
Schedule2.add_event(Event6)
Schedule2.add_event(Event7)
Schedule2.add_event(Event8)
Schedule2.add_event(Event9)
Schedule2.add_event(Event10)
Schedule2.add_event(Event11)
Schedule2.add_event(Event12)
Schedule2.add_event(Event13)
Schedule2.add_event(Event14)
Schedule2.add_event(Event15)
Schedule2.add_event(Event16)
Person1 = multi_room_model.Person('Musculation', 1, schedule = Schedule1, exposure_model=np.array([]))
Person2 = multi_room_model.Person('Concert musician rock', 2, schedule = Schedule2, exposure_model=np.array([]))

Simulation = multi_room_model.Simulation("SARS_CoV_2_OMICRON",np.array([]),np.array([]))
Simulation.add_person(Person1)
Simulation.add_person(Person2)
Simulation.add_room(Room1)
Simulation.add_room(Room2)

Report = multi_room_model.Report(np.array([]))

MultiReport = multi_room_generator.MultiGenerator(Simulation, Report)

MultiReport.calculate_simulation_data()

print(MultiReport.report.simulations[0].people[0].infection_probability)
print(MultiReport.report.simulations[0].people[1].infection_probability)
print(MultiReport.report.simulations[1].people[1].infection_probability)
print(MultiReport.report.simulations[1].people[0].infection_probability)
print(MultiReport.report.simulations[1].rooms[0].cumulative_exposure.mean())